# Generated by Django 5.2 on 2025-05-03 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Người dùng', 'verbose_name_plural': 'Người dùng'},
        ),
        migrations.AlterModelOptions(
            name='userhealthprofile',
            options={'verbose_name': 'Hồ sơ sức khỏe', 'verbose_name_plural': 'Hồ sơ sức khỏe'},
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Địa chỉ email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Đã xác thực'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='userhealthprofile',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='Dị ứng'),
        ),
        migrations.AlterField(
            model_name='userhealthprofile',
            name='blood_type',
            field=models.CharField(blank=True, max_length=5, verbose_name='Nhóm máu'),
        ),
        migrations.AlterField(
            model_name='userhealthprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='userhealthprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Người liên hệ khẩn cấp'),
        ),
        migrations.AlterField(
            model_name='userhealthprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='SĐT khẩn cấp'),
        ),
        migrations.AlterField(
            model_name='userhealthprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Chiều cao (cm)'),
        ),
        migrations.AlterField(
            model_name='userhealthprofile',
            name='medical_conditions',
            field=models.TextField(blank=True, verbose_name='Bệnh lý'),
        ),
        migrations.AlterField(
            model_name='userhealthprofile',
            name='medications',
            field=models.TextField(blank=True, verbose_name='Thuốc đang dùng'),
        ),
        migrations.AlterField(
            model_name='userhealthprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='userhealthprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='userhealthprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cân nặng (kg)'),
        ),
    ]
