import unicodedata
import re

def normalize_input(text):
    # Hàm chuẩn hóa: xóa dấu tiếng Việt và chuyển thành chữ thường
    text = text.lower()
    text = unicodedata.normalize('NFD', text)
    text = ''.join(c for c in text if unicodedata.category(c) != 'Mn')
    return text

def normalize_and(input_str):
    # Replace all forms of "va", "và" (with or without accents, with/without spaces) with a standard "và"
    input_str = re.sub(r'\bva\b', 'và', input_str, flags=re.IGNORECASE)
    return input_str

def predict_disease(text):
    text = normalize_input(text)
    
    # Định nghĩa các triệu chứng và bệnh tương ứng
    symptoms_map = {
        ("sot", "ho", "kho tho"): "Viêm phổi",
        ("sot", "phat ban"): "Sởi",
        ("sot", "dau dau"): "Cảm cúm",
        ("sot", "met moi", "kho tho", "mat vi giac"): "COVID-19",
        ("sot", "dau bung", "non"): "Ngộ độc thực phẩm",
        ("dau bung", "tieu chay"): "Ngộ độc thực phẩm",
        ("dau bung",): "Rối loạn tiêu hóa",
        ("dau hong",): "Viêm họng",
        ("dau lung",): "Thoát vị đĩa đệm hoặc đau cơ lưng",
        ("dau nguc", "kho tho"): "Bệnh tim mạch",
        ("dau tim", "mo hoi", "buon non"): "Nhồi máu cơ tim",
        ("kho tho", "tim dap nhanh", "chong mat"): "Thiếu máu cơ tim",
        ("chay mau cam",): "Thiếu vitamin C hoặc tăng huyết áp",
        ("met moi", "sut can"): "Bệnh tiểu đường",
        ("met moi", "chan an"): "Suy dinh dưỡng",
        ("dau dau", "buon non", "cung co"): "Viêm màng não",
        ("sung dau khop",): "Viêm khớp",
        ("ngua", "noi man do"): "Dị ứng da",
        ("kho tho", "ho ra mau"): "Lao phổi",
        ("mat ngu", "lo au"): "Trầm cảm",
        ("tieu nhieu", "khat nuoc", "met moi"): "Bệnh tiểu đường",
        ("vang da", "vang mat"): "Viêm gan",
        ("noi hach", "sut can"): "Ung thư hạch",
        ("dau tai", "sot"): "Viêm tai giữa",
        ("buon non", "non", "dau da day"): "Viêm loét dạ dày",
        ("rung toc", "kho da"): "Suy tuyến giáp",
        ("kho nuot", "dau hong keo dai"): "Ung thư vòm họng",
        ("sung mat ca chan", "kho tho"): "Suy tim",
        ("chay mau chan rang",): "Thiếu vitamin C",
        ("dau khop buoi sang",): "Viêm khớp dạng thấp",
        ("rung toc nhieu",): "Thiếu sắt",
        ("dau dau", "hoa mat", "chong mat"): "Thiếu máu",
        ("sot", "mo hoi dem", "giam can khong ro ly do"): "Lao phổi",
        ("man do", "da bong troc"): "Viêm da cơ địa",
        ("kho tho khi gang suc",): "Hen suyễn",
        ("kho tho khi nam",): "Suy tim",
        ("suy nhuoc co the",): "Suy dinh dưỡng",
        ("rung toc", "mong tay de gay"): "Thiếu kẽm",
        ("mat do", "ngua mat"): "Viêm kết mạc",
        ("mat tieng", "khan tieng keo dai"): "Viêm thanh quản",
        ("tieu chay keo dai",): "Hội chứng ruột kích thích",
        ("buon non", "chan an", "vang da"): "Viêm gan",
        ("dau da day",): "Viêm loét dạ dày",
        ("dau xuong", "gay xuong de dang"): "Loãng xương",
        ("mat ngu keo dai",): "Rối loạn lo âu",
        ("sung dau amidan",): "Viêm amidan",
        ("dau khop hang", "han che van dong"): "Thoái hóa khớp háng",
        ("sung dau ngon tay",): "Gout",
        ("met moi keo dai", "dau co", "tram cam"): "Hội chứng mệt mỏi mạn tính",
        ("dau dau vung tran", "nghet mui"): "Viêm xoang",
        ("met moi", "da xanh xao"): "Thiếu máu",
        ("cung co", "run tay chan"): "Bệnh Parkinson",
        ("tieu dem nhieu lan",): "Bệnh thận",
        ("dau mat", "chay nuoc mat"): "Viêm kết mạc",
        ("sot", "phat ban", "hach to"): "Sốt xuất huyết",
        ("dau da day sau an",): "Viêm loét dạ dày tá tràng",
        ("kho tieu", "day bung", "o hoi"): "Trào ngược dạ dày thực quản",
        ("kho tap trung", "met moi", "ngu gat ban ngay"): "Ngưng thở khi ngủ",
        ("noi hach co",): "Viêm hạch",
        ("nong rat da day",): "Trào ngược axit",
        ("lanh chan tay",): "Thiếu máu hoặc suy giáp",
        ("dau rat khi tieu",): "Viêm đường tiết niệu",
        ("tieu ra mau",): "Sỏi thận",
        ("tieu buot",): "Viêm bàng quang",
        ("dau vung that lung", "sot cao"): "Viêm thận",
        ("chan an", "buon non", "vang da"): "Viêm gan A",
        ("met", "mat mo", "khat nuoc lien tuc"): "Đái tháo đường",
        ("dau khop goi", "sung tay", "han che van dong"): "Thoái hóa khớp",
        ("ngua vung kin", "dich tiet bat thuong"): "Viêm nhiễm phụ khoa",
        ("sung nuou", "dau rang", "chay mau nuou"): "Viêm nha chu",
        ("mat tri nho", "lu lan", "thay doi hanh vi"): "Alzheimer",
        ("kho tho khi gang suc", "ho nhieu ve dem"): "Hen phế quản",
        ("met moi", "dau nhuc co the", "kho chiu"): "Cảm lạnh",
        ("dau hong", "khan tieng", "kho nuot"): "Viêm thanh quản mãn tính",
         ("dau bung", "dau lung", "tieu buot"): "Sỏi thận",
    ("dau hong", "ho kho", "so mui"): "Cảm lạnh thông thường",
    ("sot cao", "phat ban", "dau khop"): "Sốt phát ban",
    ("chong mat", "mo hoi", "non"): "Hạ đường huyết",
    ("tim dap nhanh", "kho tho", "da xanh xao"): "Thiếu máu nặng",
    ("ngua da", "phat ban", "mun nuoc"): "Thủy đậu",
    ("ho", "kho tho", "kho tap trung"): "Hen suyễn mãn tính",
    ("sot", "dau hong", "phat ban", "dau co"): "Sốt tinh hồng nhiệt",
    ("tuc nguc", "tim dap nhanh", "choang vang"): "Rối loạn nhịp tim",
    ("dau mat", "nhin mo", "mat thang bang"): "Glôcôm (tăng nhãn áp)",
    ("tieu chay", "non", "mat nuoc"): "Viêm dạ dày ruột",
    ("ngua", "noi mun", "tray xuoc da"): "Viêm da tiếp xúc",
    ("dau lung", "te chan tay"): "Thoát vị đĩa đệm",
    ("kho nuot", "dau nguc", "ho dai dang"): "Ung thư thực quản",
    ("da vang", "phan nhat mau", "nuoc tieu dam"): "Viêm gan B",
    ("buon non", "met moi", "tieu chay"): "Nhiễm trùng thực phẩm",
    ("dau khop", "phat ban", "sot"): "Lupus ban đỏ hệ thống",
    ("ngua mat", "mat do", "dich mat vang"): "Viêm kết mạc do vi khuẩn",
    ("ho", "dau hong", "kho tho"): "Viêm phế quản",
    ("te buot chan tay", "khong cam giac", "yeu co"): "Bệnh thần kinh ngoại biên",
    ("mat ngu", "lo au", "hoang tuong"): "Rối loạn lo âu toàn thể",
    ("dau co", "cung co", "met moi"): "Hội chứng đau cơ xơ hóa",
    ("da bong troc", "do da", "ngua da"): "Nấm da",
    ("mat ngon", "te buot ngon tay", "run tay"): "Hội chứng ống cổ tay",
    ("ho nhieu", "kho tho", "giam can"): "Ung thư phổi",
    ("dau khop", "dau lung", "giam chieu cao"): "Loãng xương nặng",
    ("dau hong", "khan tieng", "mat tieng"): "Polyp dây thanh",
    ("ngua vung kin", "mui hoi", "dich bat thuong"): "Nhiễm nấm âm đạo",
    ("di tieu it", "phu tay chan", "met moi"): "Suy thận",
    ("chay mau cam", "da xanh", "de bam tim"): "Bệnh máu khó đông",
    ("dau da day", "an khong tieu", "buon non"): "Viêm dạ dày mạn tính",
    ("tieu dem", "tieu buot", "dau lung"): "Viêm bàng quang",
    ("sot", "phat ban", "non", "met moi"): "Rubella",
    ("moi mieng", "nhiem trung mieng"): "Nhiễm nấm miệng",
    ("dau xuong", "te moi", "de gay xuong"): "Bệnh Paget xương",
    ("chong mat", "non", "di chao dao"): "Rối loạn tiền đình",
    ("ho keo dai", "tuc nguc", "kho tho"): "COPD (bệnh phổi tắc nghẽn mạn tính)",
    ("chay nuoc mui", "ho", "ngua hong"): "Cúm",
    ("phu mat", "ngua da", "kho tho"): "Phản vệ (dị ứng nặng)",
    ("dau bung", "tieu ra mau", "giam can"): "Ung thư đại tràng",
    ("non", "dau dau", "cam thay lanh"): "Viêm dạ dày ruột do virus",
    ("da xanh", "met moi", "tim dap nhanh"): "Thiếu máu thiếu sắt",
    ("met moi", "da vang", "chan an"): "Ung thư gan",
    ("dau hong", "dau tai", "so mui"): "Viêm họng cấp",
    ("phat ban", "ngua", "man do"): "Bệnh chàm",
    ("met moi", "da kho", "cham lon"): "Suy tuyến thượng thận",
    ("day bung", "o hoi", "an khong ngon"): "Viêm túi mật",
    ("ngua chan tay", "kho da", "nứt da"): "Viêm da cơ địa",
    ("ho", "tieu ra mau", "giam can"): "Ung thư phổi tiến triển",
    ("te moi", "kho thinh giac", "chong mat"): "Bệnh Meniere",
    ("ngua vung kin", "dau khi quan he"): "Viêm âm đạo",
    ("ho", "sot", "kho tho", "da xanh"): "Bệnh bạch cầu",
    ("tuc nguc", "non", "tim dap nhanh"): "Cơn đau thắt ngực",
    ("kho tho", "tim dap nhanh", "phu mat"): "Suy tim sung huyết",
    ("buon non", "day bung", "dau bung tren"): "Trào ngược dạ dày thực quản",
    ("kho ngu", "cang thang", "tram cam"): "Rối loạn lo âu",
    ("mat tieng", "dau hong", "ngua hong"): "Viêm dây thanh quản",
    ("ngua da", "phat ban", "bung rop"): "Zona thần kinh",
    ("kho tho", "ho ra mau", "met moi"): "Lao phổi tiến triển",
    }

    # Tìm các triệu chứng trong câu người dùng
    found_symptoms = []
    for symptoms in symptoms_map.keys():
        for symptom in symptoms:
            if symptom in text:
                found_symptoms.append(symptom)

    # Kiểm tra các bệnh có thể
    possible_diseases = []
    for symptoms, disease in symptoms_map.items():
        # Đếm số triệu chứng khớp
        matching_symptoms = sum(1 for symptom in symptoms if symptom in found_symptoms)
        # Nếu có ít nhất 2/3 số triệu chứng khớp hoặc tất cả triệu chứng khớp
        if matching_symptoms >= 2 and matching_symptoms >= len(symptoms) * 0.6:
            possible_diseases.append(disease)

    if possible_diseases:
        return f"Có thể bạn đang bị {' hoặc '.join(possible_diseases)}. Bạn nên đi khám để được tư vấn kỹ hơn."
    
    return "Không xác định bệnh"

# Lời khuyên cho từng bệnh (mẫu, bạn có thể sửa lại nội dung cho phù hợp)
DISEASE_ADVICE = {
    "Viêm phổi": "Bạn nên đi khám bác sĩ càng sớm càng tốt để được chẩn đoán và điều trị phù hợp. Không tự ý dùng thuốc.",
    "Sởi": "Bạn nên nghỉ ngơi, uống nhiều nước và theo dõi triệu chứng. Nếu có dấu hiệu nặng, hãy đi khám bác sĩ.",
    "Cảm cúm": "Bạn nên nghỉ ngơi, uống nhiều nước, ăn uống đầy đủ dinh dưỡng và theo dõi thân nhiệt. Nếu sốt cao kéo dài, hãy đi khám bác sĩ.",
    "COVID-19": "Bạn nên tự cách ly, đeo khẩu trang, uống nhiều nước và liên hệ cơ sở y tế nếu có triệu chứng nặng.",
    "Ngộ độc thực phẩm": "Bạn nên uống nhiều nước, tránh ăn thực phẩm nghi ngờ và đi khám nếu triệu chứng nặng.",
    "Rối loạn tiêu hóa": "Bạn nên ăn uống nhẹ nhàng, tránh thực phẩm khó tiêu và theo dõi triệu chứng.",
    "Viêm họng": "Bạn nên uống nước ấm, tránh đồ lạnh và nghỉ ngơi. Nếu đau họng kéo dài, hãy đi khám.",
    "Thoát vị đĩa đệm hoặc đau cơ lưng": "Bạn nên nghỉ ngơi, tránh mang vác nặng và đi khám chuyên khoa nếu đau kéo dài.",
    "Bệnh tim mạch": "Bạn nên đi khám bác sĩ chuyên khoa tim mạch để được tư vấn và điều trị phù hợp.",
    "Nhồi máu cơ tim": "Bạn cần đến cơ sở y tế ngay lập tức nếu có triệu chứng nghi ngờ nhồi máu cơ tim.",
    "Thiếu máu cơ tim": "Bạn nên đi khám bác sĩ để được chẩn đoán và điều trị kịp thời.",
    "Thiếu vitamin C hoặc tăng huyết áp": "Bạn nên bổ sung vitamin C qua thực phẩm và kiểm tra huyết áp định kỳ.",
    "Bệnh tiểu đường": "Bạn nên kiểm soát chế độ ăn, tập thể dục đều đặn và tuân thủ điều trị của bác sĩ.",
    "Suy dinh dưỡng": "Bạn nên bổ sung dinh dưỡng hợp lý và đi khám chuyên khoa dinh dưỡng.",
    "Viêm màng não": "Bạn nên đi khám bác sĩ ngay nếu nghi ngờ viêm màng não.",
    "Viêm khớp": "Bạn nên vận động nhẹ nhàng, tránh lạnh và đi khám chuyên khoa xương khớp.",
    "Dị ứng da": "Bạn nên tránh tiếp xúc với dị nguyên và sử dụng thuốc theo chỉ định bác sĩ.",
    "Lao phổi": "Bạn nên đi khám chuyên khoa lao phổi để được điều trị đúng cách.",
    "Trầm cảm": "Bạn nên chia sẻ với người thân và tìm sự hỗ trợ từ chuyên gia tâm lý.",
    "Viêm gan": "Bạn nên kiểm tra chức năng gan định kỳ và tuân thủ điều trị của bác sĩ.",
    "Ung thư hạch": "Bạn nên đi khám chuyên khoa ung bướu để được tư vấn và điều trị.",
    "Viêm tai giữa": "Bạn nên giữ vệ sinh tai và đi khám nếu đau hoặc chảy dịch.",
    "Viêm loét dạ dày": "Bạn nên ăn uống điều độ, tránh đồ cay nóng và tuân thủ điều trị của bác sĩ.",
    "Suy tuyến giáp": "Bạn nên kiểm tra chức năng tuyến giáp và dùng thuốc theo chỉ định.",
    "Ung thư vòm họng": "Bạn nên đi khám chuyên khoa tai mũi họng để được chẩn đoán sớm.",
    "Suy tim": "Bạn nên hạn chế muối, theo dõi cân nặng và tuân thủ điều trị của bác sĩ.",
    "Thiếu vitamin C": "Bạn nên bổ sung vitamin C qua thực phẩm như cam, chanh, bưởi.",
    "Viêm khớp dạng thấp": "Bạn nên vận động nhẹ nhàng và dùng thuốc theo chỉ định bác sĩ.",
    "Thiếu sắt": "Bạn nên bổ sung thực phẩm giàu sắt và đi khám nếu triệu chứng kéo dài.",
    "Thiếu máu": "Bạn nên bổ sung dinh dưỡng hợp lý và đi khám để xác định nguyên nhân.",
    "Viêm da cơ địa": "Bạn nên giữ ẩm da, tránh gãi và dùng thuốc theo chỉ định.",
    "Hen suyễn": "Bạn nên tránh dị nguyên, mang theo thuốc xịt và đi khám định kỳ.",
    "Ngưng thở khi ngủ": "Bạn nên đi khám chuyên khoa hô hấp để được tư vấn điều trị.",
    "Viêm hạch": "Bạn nên đi khám nếu hạch sưng to hoặc đau kéo dài.",
    "Trào ngược axit": "Bạn nên tránh ăn khuya, hạn chế đồ cay nóng và đi khám nếu triệu chứng kéo dài.",
    "Thiếu máu hoặc suy giáp": "Bạn nên kiểm tra sức khỏe định kỳ và bổ sung dinh dưỡng hợp lý.",
    "Viêm đường tiết niệu": "Bạn nên uống nhiều nước và đi khám nếu tiểu buốt kéo dài.",
    "Sỏi thận": "Bạn nên uống nhiều nước, hạn chế muối và đi khám chuyên khoa tiết niệu.",
    "Viêm bàng quang": "Bạn nên uống nhiều nước và giữ vệ sinh cá nhân.",
    "Viêm thận": "Bạn nên đi khám chuyên khoa thận để được điều trị phù hợp.",
    "Viêm gan A": "Bạn nên nghỉ ngơi, ăn uống hợp lý và theo dõi chức năng gan.",
    "Đái tháo đường": "Bạn nên kiểm soát đường huyết, ăn uống hợp lý và tập thể dục đều đặn.",
    "Thoái hóa khớp": "Bạn nên vận động nhẹ nhàng và dùng thuốc theo chỉ định bác sĩ.",
    "Viêm nhiễm phụ khoa": "Bạn nên giữ vệ sinh vùng kín và đi khám phụ khoa định kỳ.",
    "Viêm nha chu": "Bạn nên vệ sinh răng miệng sạch sẽ và đi khám nha sĩ.",
    "Alzheimer": "Bạn nên duy trì hoạt động trí não và đi khám chuyên khoa thần kinh.",
    "Hen phế quản": "Bạn nên tránh dị nguyên, mang theo thuốc xịt và đi khám định kỳ.",
    "Cảm lạnh": "Bạn nên nghỉ ngơi, uống nhiều nước và theo dõi triệu chứng.",
    "Viêm thanh quản mãn tính": "Bạn nên hạn chế nói to, tránh khói bụi và đi khám chuyên khoa.",
    "Sỏi thận": "Bạn nên uống nhiều nước, hạn chế muối và đi khám chuyên khoa tiết niệu.",
    "Cảm lạnh thông thường": "Bạn nên nghỉ ngơi, uống nhiều nước và theo dõi triệu chứng.",
    "Sốt phát ban": "Bạn nên nghỉ ngơi, uống nhiều nước và theo dõi triệu chứng.",
    "Hạ đường huyết": "Bạn nên bổ sung đường nhanh và đi khám nếu triệu chứng không cải thiện.",
    "Thiếu máu nặng": "Bạn nên đi khám để được truyền máu hoặc điều trị phù hợp.",
    "Thủy đậu": "Bạn nên nghỉ ngơi, tránh gãi và giữ vệ sinh da.",
    "Hen suyễn mãn tính": "Bạn nên tránh dị nguyên, mang theo thuốc xịt và đi khám định kỳ.",
    "Sốt tinh hồng nhiệt": "Bạn nên đi khám bác sĩ để được chẩn đoán và điều trị phù hợp.",
    "Rối loạn nhịp tim": "Bạn nên đi khám chuyên khoa tim mạch để được tư vấn.",
    "Glôcôm (tăng nhãn áp)": "Bạn nên đi khám chuyên khoa mắt để được điều trị kịp thời.",
    "Viêm dạ dày ruột": "Bạn nên uống nhiều nước, ăn uống nhẹ nhàng và đi khám nếu tiêu chảy kéo dài.",
    "Viêm da tiếp xúc": "Bạn nên tránh tiếp xúc với dị nguyên và dùng thuốc theo chỉ định.",
    "Thoát vị đĩa đệm": "Bạn nên nghỉ ngơi, tránh mang vác nặng và đi khám chuyên khoa nếu đau kéo dài.",
    "Ung thư thực quản": "Bạn nên đi khám chuyên khoa ung bướu để được tư vấn và điều trị.",
    "Viêm gan B": "Bạn nên kiểm tra chức năng gan định kỳ và tuân thủ điều trị của bác sĩ.",
    "Nhiễm trùng thực phẩm": "Bạn nên uống nhiều nước, tránh ăn thực phẩm nghi ngờ và đi khám nếu triệu chứng nặng.",
    "Lupus ban đỏ hệ thống": "Bạn nên đi khám chuyên khoa miễn dịch để được tư vấn.",
    "Viêm kết mạc do vi khuẩn": "Bạn nên giữ vệ sinh mắt và dùng thuốc theo chỉ định bác sĩ.",
    "Viêm phế quản": "Bạn nên nghỉ ngơi, uống nhiều nước và đi khám nếu ho kéo dài.",
    "Bệnh thần kinh ngoại biên": "Bạn nên đi khám chuyên khoa thần kinh để được tư vấn.",
    "Rối loạn lo âu toàn thể": "Bạn nên chia sẻ với người thân và tìm sự hỗ trợ từ chuyên gia tâm lý.",
    "Hội chứng đau cơ xơ hóa": "Bạn nên vận động nhẹ nhàng và đi khám chuyên khoa cơ xương khớp.",
    "Nấm da": "Bạn nên giữ vệ sinh da và dùng thuốc theo chỉ định bác sĩ.",
    "Hội chứng ống cổ tay": "Bạn nên nghỉ ngơi, tránh vận động lặp lại và đi khám nếu đau kéo dài.",
    "Ung thư phổi": "Bạn nên đi khám chuyên khoa ung bướu để được tư vấn và điều trị.",
    "Loãng xương nặng": "Bạn nên bổ sung canxi, vitamin D và vận động hợp lý.",
    "Polyp dây thanh": "Bạn nên hạn chế nói to, tránh khói bụi và đi khám chuyên khoa.",
    "Nhiễm nấm âm đạo": "Bạn nên giữ vệ sinh vùng kín và đi khám phụ khoa định kỳ.",
    "Suy thận": "Bạn nên kiểm tra chức năng thận định kỳ và tuân thủ điều trị của bác sĩ.",
    "Bệnh máu khó đông": "Bạn nên tránh va chạm mạnh và đi khám chuyên khoa huyết học.",
    "Viêm dạ dày mạn tính": "Bạn nên ăn uống điều độ, tránh đồ cay nóng và tuân thủ điều trị của bác sĩ.",
    "Viêm bàng quang": "Bạn nên uống nhiều nước và giữ vệ sinh cá nhân.",
    "Rubella": "Bạn nên nghỉ ngơi, uống nhiều nước và theo dõi triệu chứng.",
    "Nhiễm nấm miệng": "Bạn nên giữ vệ sinh răng miệng và dùng thuốc theo chỉ định.",
    "Bệnh Paget xương": "Bạn nên đi khám chuyên khoa xương khớp để được tư vấn.",
    "Rối loạn tiền đình": "Bạn nên nghỉ ngơi, tránh thay đổi tư thế đột ngột và đi khám nếu chóng mặt kéo dài.",
    "COPD (bệnh phổi tắc nghẽn mạn tính)": "Bạn nên tránh khói thuốc, bụi bẩn và tuân thủ điều trị của bác sĩ.",
    "Cúm": "Bạn nên nghỉ ngơi, uống nhiều nước và theo dõi triệu chứng.",
    "Phản vệ (dị ứng nặng)": "Bạn cần đến cơ sở y tế ngay lập tức nếu có dấu hiệu phản vệ.",
    "Ung thư đại tràng": "Bạn nên đi khám chuyên khoa ung bướu để được tư vấn và điều trị.",
    "Viêm dạ dày ruột do virus": "Bạn nên uống nhiều nước, ăn uống nhẹ nhàng và đi khám nếu tiêu chảy kéo dài.",
    "Thiếu máu thiếu sắt": "Bạn nên bổ sung thực phẩm giàu sắt và đi khám nếu triệu chứng kéo dài.",
    "Ung thư gan": "Bạn nên đi khám chuyên khoa ung bướu để được tư vấn và điều trị.",
    "Viêm họng cấp": "Bạn nên uống nước ấm, tránh đồ lạnh và nghỉ ngơi. Nếu đau họng kéo dài, hãy đi khám.",
    "Bệnh chàm": "Bạn nên giữ ẩm da, tránh gãi và dùng thuốc theo chỉ định.",
    "Suy tuyến thượng thận": "Bạn nên kiểm tra chức năng tuyến thượng thận và dùng thuốc theo chỉ định.",
    "Viêm túi mật": "Bạn nên ăn uống nhẹ nhàng, tránh đồ dầu mỡ và đi khám nếu đau kéo dài.",
    "Viêm da cơ địa": "Bạn nên giữ ẩm da, tránh gãi và dùng thuốc theo chỉ định.",
    "Ung thư phổi tiến triển": "Bạn nên đi khám chuyên khoa ung bướu để được tư vấn và điều trị.",
    "Bệnh Meniere": "Bạn nên đi khám chuyên khoa tai mũi họng để được tư vấn.",
    "Viêm âm đạo": "Bạn nên giữ vệ sinh vùng kín và đi khám phụ khoa định kỳ.",
    "Bệnh bạch cầu": "Bạn nên đi khám chuyên khoa huyết học để được tư vấn và điều trị.",
    "Cơn đau thắt ngực": "Bạn nên đi khám chuyên khoa tim mạch để được tư vấn.",
    "Suy tim sung huyết": "Bạn nên hạn chế muối, theo dõi cân nặng và tuân thủ điều trị của bác sĩ.",
    "Trào ngược dạ dày thực quản": "Bạn nên tránh ăn khuya, hạn chế đồ cay nóng và đi khám nếu triệu chứng kéo dài.",
    "Rối loạn lo âu": "Bạn nên chia sẻ với người thân và tìm sự hỗ trợ từ chuyên gia tâm lý.",
    "Viêm dây thanh quản": "Bạn nên hạn chế nói to, tránh khói bụi và đi khám chuyên khoa.",
    "Zona thần kinh": "Bạn nên nghỉ ngơi, tránh gãi và giữ vệ sinh da.",
    "Lao phổi tiến triển": "Bạn nên đi khám chuyên khoa lao phổi để được điều trị đúng cách."
}

